print("Please enter the number of lives")
lives = int(input())
print("PLease enter the energy level")
level = int(input())
print("Please enter the shield level")
level = int(input())
print("Health has been set")
